<?php
namespace Home\Model;
use Think\Model;

class ClassModel extends Model{

    protected $tableName = 'class';
    protected static $parents = [];

	//返回指定ID对应的所有子栏目
	public function getChildClass($id) {

		$classIdArr = array();
		$condition['father_id'] = $id;
		$classArr = $this->where($condition)->select();

		foreach ($classArr as $k=>$v) {
			$classIdArr[] = $v['class_id'];
		}

		if (empty($classIdArr)) {
			$classIdArr[] = $id;	
		}
		return $classIdArr;
	}

    /*public function getTemplate($class_id)
    {
        return $this->where(['class_id'=>$class_id])->join('INNER JOIN __TEMPLATE__ ON __CLASS__.index_template = __TEMPLATE.template_id')->select();
    }*/
    /**
     * 获取所有的父级栏目
     * @return array
     */
	public function getParents(){
        if(count(self::$parents)<=0){
            //todo ['is_nav'=>1]
            self::$parents = $this->where([['father_id'=>0],['is_show'=>1]])->order('sort_index desc')->select();
        }
        return self::$parents;
    }

	public function getChildClassArr($id) {
		$condition['father_id'] = $id;
		$classArr = $this->where($condition)->select();
		return $classArr;
	}
	/*public function scope($scope = '', $args = NULL)
    {
        return parent::scope($scope, $args); // TODO: Change the autogenerated stub
    }*/

}